name: CI

on:
  schedule:
    - cron: 0 2 * * 1-5
  pull_request:

jobs:
  tests:
    name: Tests PHP ${{ matrix.php }} ${{ matrix.dependency }}
    runs-on: ubuntu-latest
    container:
      image: php:${{ matrix.php }}-fpm-alpine
      options: >-
        --tmpfs /tmp:exec
    strategy:
      # https://github.community/t5/GitHub-Actions/GitHub-Actions-Matrix-options-dont-work-as-documented/m-p/29558
      matrix:
        php:
          - '7.2'
          - '7.3'
          - '7.4'
        dependency:
          - ''
          - 'lowest'
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache
          key: ${{ matrix.php }}-composer-${{ matrix.dependency }}-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            ${{ matrix.php }}-composer-${{ matrix.dependency }}-

      - name: Install Composer
        run: curl -sS -o - https://raw.githubusercontent.com/composer/getcomposer.org/ba13e3fc70f1c66250d1ea7ea4911d593aa1dba5/web/installer | php -- --install-dir=/usr/local/bin --filename=composer --quiet

      - name: Update project dependencies
        if: matrix.dependency == ''
        run: composer update --no-progress --no-suggest --ansi

      - name: Update project dependencies lowest
        if: matrix.dependency == 'lowest'
        run: composer update --no-progress --no-suggest --ansi --prefer-lowest

      - name: Run phpstan tests
        if: matrix.dependency == ''
        run: vendor/bin/phpstan analyze

      - name: Run php-cs-fixer tests
        run: vendor/bin/php-cs-fixer fix --dry-run --diff

      - name: Run PHPUnit tests
        run: vendor/bin/phpunit --colors=always --testdox
